#!/usr/bin/env bash
# What type of network a computer in local # is connected to?
# What type of network could connect an off# ice in one building to another office in # a building a few streets away?
# What network do you use when you browse w# ww.google.com from your smartphone (not
# connected to the Wifi)?

3
2
1
