#!/usr/bin/env bash
# Displays information about the file "school"

if [ -e "School" ]
then
    echo "School file is not  empty"
else
    echo "School file is empty"
fi
    if [ -f "school" ]
    then 
        echo "school is a regular file"
fi
    else
          echo "school file does not exist"
fi
