#!/usr/bin/env bash
# a Bash script that configures an Ubuntu server
# with the below requirements:
# localhost resolves to 127.0.0.2
# facebook.com resolves to 8.8.8.8.
# The checker is running on Docker, so make sure
# to read thislocalhost resolves to 127.0.0.2
# facebook.com resolves to 8.8.8.8.

cp /etc/hosts ~/hosts.new
echo "127.0.0.2 localhost" > ~/localhost.new
echo "8.8.8.8 facebook.com" >> ~/localhost.new
cp -f ~/hosts.new /etc/hosts
